language: android
sudo: true
android:
  components:
    - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
addons:
  apt_packages:
    - pandoc
    - realpath
    - wget
    - curl

#  artifacts:
#    paths:
#      - $(git ls-files -o | grep app/build/outputs | tr "\n" ":")
before_install:
  - sudo apt-get install ant
install:
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "lldb;3.1"
  - sdkmanager --uninstall "ndk-bundle"
    #  - sdkmanager --update
before_script:
  - export ANDROID_NDK_HOME=

script:
  # scripts excutes inside our repo directory on CI machine
  - export SAMPLE_CI_RESULT=0

  # download android-ndk
  - source ./scripts/get-release.sh

  # download android-ndk repo
  - git clone https://github.com/googlesamples/android-ndk.git ../android-ndk
  - cd ../android-ndk

  # Followings would be executing from android-ndk home dir
  - source .ci_tools/setup_env.sh
  - source .ci_tools/build_samples.sh
  - source .ci_tools/run_samples.sh
  - source .ci_tools/misc_ci.sh
  - eval "[[ $SAMPLE_CI_RESULT == 0 ]]"
